<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 15 Dec 2025 15:10:45 +0000
 */

$conf['title'] = 'Uprzejme Wiki';
$conf['lang'] = 'pl';
$conf['license'] = 'cc-by-sa';
$conf['disableactions'] = 'register';

$conf['basedir']    = '/wiki/';
$conf['baseurl']    = 'https://uprzejmiedonosze.net/wiki/';
$conf['cookiedir']  = '/wiki/';

$conf['userewrite'] = 1;    // Włącza mechanizm Nice URLs (Server rewrite)
$conf['useslash']   = 1;    // Zamienia dwukropki (wiki:syntax) na ukośniki (wiki/syntax)
$conf['sepchar']    = '_';  // (Opcjonalnie) separator słów w nazwach stron
